### ISSUE TITLE
Record data problem 记录数据的问题

### ISSUE THREAD

**Issue by yzy081** [gztss/SerialTool#2]
现在保存数据只能手动保存，而且不知道这个缓存有多大。、
现在想24小时传感器记录数据，数据用串口保存的PC里，现在需要将数据可靠完整地保存到硬盘中。现在只能手动保存。而且不知道缓存有多大，如果开机24小时或者240小时，缓存应该会清空吧？
如果可以添加实时写入文件的功能就更好了。

**Comment by gztss** [comment]
* 缓存不会清空，这个缓存会一直在内存中申请。
* 如果要实时写入的功能，我建议你另外实现一个软件。因为SerialTool在接收波形数据的时候会不断地刷新显示，数据多了以后会比较占用硬件资源（建议开启GPU加速）。
